[package]
name = "shake-cursor"
version = "0.1.0"
edition = "2024"

[dependencies]
x11rb = { version = "0.13", features = ["cursor", "xinput", "xfixes"] }
signal-hook = "0.4"
log = "0.4"
env_logger = "0.11"
